version: "2.3"  # optional since v1.27.0
services:
    selenium:
        image: selenium/standalone-chrome
        environment:
            - SE_NODE_SESSION_TIMEOUT=999999
        ports:
            - "4444:4444"
    bot:
        build:
            context: .
            dockerfile: Dockerfile.selenium
        restart: on-failure
        depends_on:
            - selenium
 #       ports:
#            - "4444:4444"
